[workspace]
members = [
    "quartz-insert",
    "quartz-select",
    "quartz-storage",
    "quartz-common",
    "quartz-cli",
]

[workspace.dependencies]
anyhow = "1"
byte-unit = { version = "4", default-features = false, features = ["serde", "std"] }
bytes = "1"
arc-swap = "1.6"
assert-json-diff = "2"
async-speed-limit = "0.4"
async-trait = "0.1"
atty = "0.2"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.21"
clap = { version = "4.3.0", features = ["env", "string"] }
colored = "2.0.0"
console-subscriber = "0.1.8"
criterion = { version = "0.5", features = ["async_tokio"] }
cron = "0.11.0"
dialoguer = "0.10.3"
dotenv = "0.15"
dyn-clone = "1.0.10"
enum-iterator = "1.4"
env_logger = "0.9"
fail = "0.5"
flume = "0.10"
fnv = "1"
futures = "0.3"
futures-util = { version = "0.3.25", default-features = false }
heck = "0.4.1"
hex = "0.4.3"
hostname = "0.3"
http = "0.2.9"
http-serde = "1.1.2"
humansize = "2.1.3"
humantime = "2.1.0"
hyper = { version = "0.14", features = [
  "client",
  "http1",
  "http2",
  "server",
  "stream",
  "tcp",
] }
hyper-rustls = "0.24"
indexmap = { version = "1.9.2", features = ["serde"] }

lru = "0.10"
md5 = "0.7"
nom = "7.1.3"
num_cpus = "1"
once_cell = "1"
oneshot = "0.1.5"
pin-project = "1.1.0"
pnet = { version = "0.31.0", features = ["std"] }
postcard = { version = "1.0.4", features = ["use-std"], default-features = false}
prost = { version = "0.11.6", default-features = false, features = [
  "prost-derive",
] }
prost-build = "0.11.6"
prost-types = "0.11.6"
rand = "0.8"
rand_distr = "0.4"
rayon = "1"
regex = "1.8.1"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
rust-embed = "6.6.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_qs = { version = "0.10", features = ["warp"] }
serde_with = "2.3.0"
serde_yaml = "0.9"
serial_test = "0.9.0"
siphasher = "0.3"
sqlx = { version = "0.6", features = [
  "runtime-tokio-rustls",
  "postgres",
  "migrate",
  "time",
] }
syn = "2.0.11"
tabled = { version = "0.8", features = ["color"] }
tempfile = "3"
thiserror = "1"
thousands = "0.2.0"
tikv-jemalloc-ctl = "0.5"
tikv-jemallocator = "0.5"
time = { version = "0.3.17", features = ["std", "formatting", "macros"] }
tokio = { version = "1.28", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["full"] }
toml = "0.6.0"
tonic = { version = "0.9.0", features = ["gzip"] }
tonic-build = "0.9.0"
tower = { version = "0.4.13", features = ["balance", "buffer", "load", "util"] }
tower-http = { version = "0.4.0", features = ["compression-gzip", "cors"] }
typetag = "0.2"
ulid = "1.0"
username = "0.2"
utoipa = "3.3.0"
uuid = { version = "1.3", features = ["v4", "serde"] }
warp = "0.3"
wiremock = "0.5"

quartz-common = { version = "0.1.0", path = "./quartz-common" }
