[package]
name = "ingester"
description = "ingester for quartzdb"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tonic.workspace = true
datafusion.workspace = true
datafusion-distributed.workspace = true
arrow-flight.workspace = true
axum.workspace = true
serde.workspace = true
futures.workspace = true
async-trait.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
serde_json.workspace = true
hashbrown.workspace = true

common.workspace = true
storage.workspace = true
metastore.workspace = true
storer.workspace = true

