[package]
name = "common"
description = "A search storage engine for log and traces"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tonic.workspace = true
tonic-reflection.workspace = true
prost.workspace = true
prost-types.workspace = true
tonic-prost.workspace = true
tokio.workspace = true
anyhow.workspace = true
url.workspace = true
axum.workspace = true
hashbrown.workspace = true
json_dotpath.workspace = true
tantivy.workspace = true
datafusion.workspace = true
jiff.workspace = true
bytes.workspace = true
arrow-json.workspace = true

[build-dependencies]
prost-build.workspace = true
tonic-prost-build.workspace = true
